//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.SanPham_Service {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SanPham_Service.SanPham_ServiceSoap")]
    public interface SanPham_ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SanPham_GetAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SanPham_GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SanPham_GetByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SanPham_GetByID(int ma_sp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SanPham_GetByCategories", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SanPham_GetByCategories(int ma_loai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_SanPham", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Delete_SanPham(int ma_sp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_SanPham", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Update_SanPham(int ma_sp, string ten_sp, string mota, decimal gia, string hinh, int phanloai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_SanPham", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Insert_SanPham(string ten_sp, string mota, decimal gia, string hinh, int phanloai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDanhMuc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetDanhMuc(int ma_danhmuc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DanhMuc_Load", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable DanhMuc_Load();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SanPham_Load", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SanPham_Load();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSanPham", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetSanPham(int ma_sp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetGia(int ma_sp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SanPham_ServiceSoapChannel : Website.SanPham_Service.SanPham_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SanPham_ServiceSoapClient : System.ServiceModel.ClientBase<Website.SanPham_Service.SanPham_ServiceSoap>, Website.SanPham_Service.SanPham_ServiceSoap {
        
        public SanPham_ServiceSoapClient() {
        }
        
        public SanPham_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SanPham_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SanPham_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SanPham_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable SanPham_GetAll() {
            return base.Channel.SanPham_GetAll();
        }
        
        public System.Data.DataTable SanPham_GetByID(int ma_sp) {
            return base.Channel.SanPham_GetByID(ma_sp);
        }
        
        public System.Data.DataTable SanPham_GetByCategories(int ma_loai) {
            return base.Channel.SanPham_GetByCategories(ma_loai);
        }
        
        public bool Delete_SanPham(int ma_sp) {
            return base.Channel.Delete_SanPham(ma_sp);
        }
        
        public bool Update_SanPham(int ma_sp, string ten_sp, string mota, decimal gia, string hinh, int phanloai) {
            return base.Channel.Update_SanPham(ma_sp, ten_sp, mota, gia, hinh, phanloai);
        }
        
        public bool Insert_SanPham(string ten_sp, string mota, decimal gia, string hinh, int phanloai) {
            return base.Channel.Insert_SanPham(ten_sp, mota, gia, hinh, phanloai);
        }
        
        public string GetDanhMuc(int ma_danhmuc) {
            return base.Channel.GetDanhMuc(ma_danhmuc);
        }
        
        public System.Data.DataTable DanhMuc_Load() {
            return base.Channel.DanhMuc_Load();
        }
        
        public System.Data.DataTable SanPham_Load() {
            return base.Channel.SanPham_Load();
        }
        
        public string GetSanPham(int ma_sp) {
            return base.Channel.GetSanPham(ma_sp);
        }
        
        public string GetGia(int ma_sp) {
            return base.Channel.GetGia(ma_sp);
        }
    }
}
