//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace WindowsForms.DanhMuc_ServiceReferences {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DanhMuc_ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class DanhMuc_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DanhMuc_GetByAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback DanhMuc_GetByNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback Delete_DanhMucOperationCompleted;
        
        private System.Threading.SendOrPostCallback Update_DanhMucOperationCompleted;
        
        private System.Threading.SendOrPostCallback Insert_DanhMucOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DanhMuc_Service() {
            this.Url = global::WindowsForms.Properties.Settings.Default.WindowsForms_DanhMuc_Service_DanhMuc_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DanhMuc_GetByAllCompletedEventHandler DanhMuc_GetByAllCompleted;
        
        /// <remarks/>
        public event DanhMuc_GetByNameCompletedEventHandler DanhMuc_GetByNameCompleted;
        
        /// <remarks/>
        public event Delete_DanhMucCompletedEventHandler Delete_DanhMucCompleted;
        
        /// <remarks/>
        public event Update_DanhMucCompletedEventHandler Update_DanhMucCompleted;
        
        /// <remarks/>
        public event Insert_DanhMucCompletedEventHandler Insert_DanhMucCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DanhMuc_GetByAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable DanhMuc_GetByAll() {
            object[] results = this.Invoke("DanhMuc_GetByAll", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void DanhMuc_GetByAllAsync() {
            this.DanhMuc_GetByAllAsync(null);
        }
        
        /// <remarks/>
        public void DanhMuc_GetByAllAsync(object userState) {
            if ((this.DanhMuc_GetByAllOperationCompleted == null)) {
                this.DanhMuc_GetByAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDanhMuc_GetByAllOperationCompleted);
            }
            this.InvokeAsync("DanhMuc_GetByAll", new object[0], this.DanhMuc_GetByAllOperationCompleted, userState);
        }
        
        private void OnDanhMuc_GetByAllOperationCompleted(object arg) {
            if ((this.DanhMuc_GetByAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DanhMuc_GetByAllCompleted(this, new DanhMuc_GetByAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DanhMuc_GetByName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable DanhMuc_GetByName(string ten_loai) {
            object[] results = this.Invoke("DanhMuc_GetByName", new object[] {
                        ten_loai});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void DanhMuc_GetByNameAsync(string ten_loai) {
            this.DanhMuc_GetByNameAsync(ten_loai, null);
        }
        
        /// <remarks/>
        public void DanhMuc_GetByNameAsync(string ten_loai, object userState) {
            if ((this.DanhMuc_GetByNameOperationCompleted == null)) {
                this.DanhMuc_GetByNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDanhMuc_GetByNameOperationCompleted);
            }
            this.InvokeAsync("DanhMuc_GetByName", new object[] {
                        ten_loai}, this.DanhMuc_GetByNameOperationCompleted, userState);
        }
        
        private void OnDanhMuc_GetByNameOperationCompleted(object arg) {
            if ((this.DanhMuc_GetByNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DanhMuc_GetByNameCompleted(this, new DanhMuc_GetByNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Delete_DanhMuc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Delete_DanhMuc(int ma_loai) {
            object[] results = this.Invoke("Delete_DanhMuc", new object[] {
                        ma_loai});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Delete_DanhMucAsync(int ma_loai) {
            this.Delete_DanhMucAsync(ma_loai, null);
        }
        
        /// <remarks/>
        public void Delete_DanhMucAsync(int ma_loai, object userState) {
            if ((this.Delete_DanhMucOperationCompleted == null)) {
                this.Delete_DanhMucOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_DanhMucOperationCompleted);
            }
            this.InvokeAsync("Delete_DanhMuc", new object[] {
                        ma_loai}, this.Delete_DanhMucOperationCompleted, userState);
        }
        
        private void OnDelete_DanhMucOperationCompleted(object arg) {
            if ((this.Delete_DanhMucCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Delete_DanhMucCompleted(this, new Delete_DanhMucCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Update_DanhMuc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Update_DanhMuc(int ma_loai, string ten_loai) {
            object[] results = this.Invoke("Update_DanhMuc", new object[] {
                        ma_loai,
                        ten_loai});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Update_DanhMucAsync(int ma_loai, string ten_loai) {
            this.Update_DanhMucAsync(ma_loai, ten_loai, null);
        }
        
        /// <remarks/>
        public void Update_DanhMucAsync(int ma_loai, string ten_loai, object userState) {
            if ((this.Update_DanhMucOperationCompleted == null)) {
                this.Update_DanhMucOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdate_DanhMucOperationCompleted);
            }
            this.InvokeAsync("Update_DanhMuc", new object[] {
                        ma_loai,
                        ten_loai}, this.Update_DanhMucOperationCompleted, userState);
        }
        
        private void OnUpdate_DanhMucOperationCompleted(object arg) {
            if ((this.Update_DanhMucCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Update_DanhMucCompleted(this, new Update_DanhMucCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Insert_DanhMuc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Insert_DanhMuc(string ten_loai) {
            object[] results = this.Invoke("Insert_DanhMuc", new object[] {
                        ten_loai});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Insert_DanhMucAsync(string ten_loai) {
            this.Insert_DanhMucAsync(ten_loai, null);
        }
        
        /// <remarks/>
        public void Insert_DanhMucAsync(string ten_loai, object userState) {
            if ((this.Insert_DanhMucOperationCompleted == null)) {
                this.Insert_DanhMucOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsert_DanhMucOperationCompleted);
            }
            this.InvokeAsync("Insert_DanhMuc", new object[] {
                        ten_loai}, this.Insert_DanhMucOperationCompleted, userState);
        }
        
        private void OnInsert_DanhMucOperationCompleted(object arg) {
            if ((this.Insert_DanhMucCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Insert_DanhMucCompleted(this, new Insert_DanhMucCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DanhMuc_GetByAllCompletedEventHandler(object sender, DanhMuc_GetByAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DanhMuc_GetByAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DanhMuc_GetByAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DanhMuc_GetByNameCompletedEventHandler(object sender, DanhMuc_GetByNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DanhMuc_GetByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DanhMuc_GetByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void Delete_DanhMucCompletedEventHandler(object sender, Delete_DanhMucCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Delete_DanhMucCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Delete_DanhMucCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void Update_DanhMucCompletedEventHandler(object sender, Update_DanhMucCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Update_DanhMucCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Update_DanhMucCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void Insert_DanhMucCompletedEventHandler(object sender, Insert_DanhMucCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Insert_DanhMucCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Insert_DanhMucCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591