//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.DanhMuc_Service {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DanhMuc_Service.DanhMuc_ServiceSoap")]
    public interface DanhMuc_ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DanhMuc_GetByAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable DanhMuc_GetByAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DanhMuc_GetByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable DanhMuc_GetByID(int ma_loai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DanhMuc_GetByName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable DanhMuc_GetByName(string ten_loai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_DanhMuc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Delete_DanhMuc(int ma_loai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_DanhMuc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Update_DanhMuc(int ma_loai, string ten_loai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_DanhMuc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Insert_DanhMuc(string ten_loai);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DanhMuc_ServiceSoapChannel : Website.DanhMuc_Service.DanhMuc_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DanhMuc_ServiceSoapClient : System.ServiceModel.ClientBase<Website.DanhMuc_Service.DanhMuc_ServiceSoap>, Website.DanhMuc_Service.DanhMuc_ServiceSoap {
        
        public DanhMuc_ServiceSoapClient() {
        }
        
        public DanhMuc_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DanhMuc_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DanhMuc_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DanhMuc_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable DanhMuc_GetByAll() {
            return base.Channel.DanhMuc_GetByAll();
        }
        
        public System.Data.DataTable DanhMuc_GetByID(int ma_loai) {
            return base.Channel.DanhMuc_GetByID(ma_loai);
        }
        
        public System.Data.DataTable DanhMuc_GetByName(string ten_loai) {
            return base.Channel.DanhMuc_GetByName(ten_loai);
        }
        
        public bool Delete_DanhMuc(int ma_loai) {
            return base.Channel.Delete_DanhMuc(ma_loai);
        }
        
        public bool Update_DanhMuc(int ma_loai, string ten_loai) {
            return base.Channel.Update_DanhMuc(ma_loai, ten_loai);
        }
        
        public bool Insert_DanhMuc(string ten_loai) {
            return base.Channel.Insert_DanhMuc(ten_loai);
        }
    }
}
