//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace WindowsForms.ChiTietDonHang_ServiceReferences {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ChiTietDonHang_ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class ChiTietDonHang_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ChiTietDonHang_GetByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback SanPham_GetNameByIDOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ChiTietDonHang_Service() {
            this.Url = global::WindowsForms.Properties.Settings.Default.WindowsForms_ChiTietDonHang_ServiceReferences_ChiTietDonHang_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ChiTietDonHang_GetByIDCompletedEventHandler ChiTietDonHang_GetByIDCompleted;
        
        /// <remarks/>
        public event SanPham_GetNameByIDCompletedEventHandler SanPham_GetNameByIDCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChiTietDonHang_GetByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ChiTietDonHang_GetByID(int ma_donhang) {
            object[] results = this.Invoke("ChiTietDonHang_GetByID", new object[] {
                        ma_donhang});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ChiTietDonHang_GetByIDAsync(int ma_donhang) {
            this.ChiTietDonHang_GetByIDAsync(ma_donhang, null);
        }
        
        /// <remarks/>
        public void ChiTietDonHang_GetByIDAsync(int ma_donhang, object userState) {
            if ((this.ChiTietDonHang_GetByIDOperationCompleted == null)) {
                this.ChiTietDonHang_GetByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChiTietDonHang_GetByIDOperationCompleted);
            }
            this.InvokeAsync("ChiTietDonHang_GetByID", new object[] {
                        ma_donhang}, this.ChiTietDonHang_GetByIDOperationCompleted, userState);
        }
        
        private void OnChiTietDonHang_GetByIDOperationCompleted(object arg) {
            if ((this.ChiTietDonHang_GetByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChiTietDonHang_GetByIDCompleted(this, new ChiTietDonHang_GetByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SanPham_GetNameByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SanPham_GetNameByID(int ma_sp) {
            object[] results = this.Invoke("SanPham_GetNameByID", new object[] {
                        ma_sp});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void SanPham_GetNameByIDAsync(int ma_sp) {
            this.SanPham_GetNameByIDAsync(ma_sp, null);
        }
        
        /// <remarks/>
        public void SanPham_GetNameByIDAsync(int ma_sp, object userState) {
            if ((this.SanPham_GetNameByIDOperationCompleted == null)) {
                this.SanPham_GetNameByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSanPham_GetNameByIDOperationCompleted);
            }
            this.InvokeAsync("SanPham_GetNameByID", new object[] {
                        ma_sp}, this.SanPham_GetNameByIDOperationCompleted, userState);
        }
        
        private void OnSanPham_GetNameByIDOperationCompleted(object arg) {
            if ((this.SanPham_GetNameByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SanPham_GetNameByIDCompleted(this, new SanPham_GetNameByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ChiTietDonHang_GetByIDCompletedEventHandler(object sender, ChiTietDonHang_GetByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChiTietDonHang_GetByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChiTietDonHang_GetByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SanPham_GetNameByIDCompletedEventHandler(object sender, SanPham_GetNameByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SanPham_GetNameByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SanPham_GetNameByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591