//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace WindowsForms.ChiTietDonHang_ServiceReferences {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ChiTietDonHang_ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class ChiTietDonHang_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ChiTietDonHang_GetByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback Delete_ChiTietDonHangOperationCompleted;
        
        private System.Threading.SendOrPostCallback Delete_SanPhamOperationCompleted;
        
        private System.Threading.SendOrPostCallback Insert_ChiTietDonHangOperationCompleted;
        
        private System.Threading.SendOrPostCallback Update_ChiTietDonHangOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ChiTietDonHang_Service() {
            this.Url = global::WindowsForms.Properties.Settings.Default.WindowsForms_ChiTietDonHang_ServiceReferences_ChiTietDonHang_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ChiTietDonHang_GetByIDCompletedEventHandler ChiTietDonHang_GetByIDCompleted;
        
        /// <remarks/>
        public event Delete_ChiTietDonHangCompletedEventHandler Delete_ChiTietDonHangCompleted;
        
        /// <remarks/>
        public event Delete_SanPhamCompletedEventHandler Delete_SanPhamCompleted;
        
        /// <remarks/>
        public event Insert_ChiTietDonHangCompletedEventHandler Insert_ChiTietDonHangCompleted;
        
        /// <remarks/>
        public event Update_ChiTietDonHangCompletedEventHandler Update_ChiTietDonHangCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChiTietDonHang_GetByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ChiTietDonHang_GetByID(int ma_donhang) {
            object[] results = this.Invoke("ChiTietDonHang_GetByID", new object[] {
                        ma_donhang});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ChiTietDonHang_GetByIDAsync(int ma_donhang) {
            this.ChiTietDonHang_GetByIDAsync(ma_donhang, null);
        }
        
        /// <remarks/>
        public void ChiTietDonHang_GetByIDAsync(int ma_donhang, object userState) {
            if ((this.ChiTietDonHang_GetByIDOperationCompleted == null)) {
                this.ChiTietDonHang_GetByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChiTietDonHang_GetByIDOperationCompleted);
            }
            this.InvokeAsync("ChiTietDonHang_GetByID", new object[] {
                        ma_donhang}, this.ChiTietDonHang_GetByIDOperationCompleted, userState);
        }
        
        private void OnChiTietDonHang_GetByIDOperationCompleted(object arg) {
            if ((this.ChiTietDonHang_GetByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChiTietDonHang_GetByIDCompleted(this, new ChiTietDonHang_GetByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Delete_ChiTietDonHang", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Delete_ChiTietDonHang(int ma_dh) {
            object[] results = this.Invoke("Delete_ChiTietDonHang", new object[] {
                        ma_dh});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Delete_ChiTietDonHangAsync(int ma_dh) {
            this.Delete_ChiTietDonHangAsync(ma_dh, null);
        }
        
        /// <remarks/>
        public void Delete_ChiTietDonHangAsync(int ma_dh, object userState) {
            if ((this.Delete_ChiTietDonHangOperationCompleted == null)) {
                this.Delete_ChiTietDonHangOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_ChiTietDonHangOperationCompleted);
            }
            this.InvokeAsync("Delete_ChiTietDonHang", new object[] {
                        ma_dh}, this.Delete_ChiTietDonHangOperationCompleted, userState);
        }
        
        private void OnDelete_ChiTietDonHangOperationCompleted(object arg) {
            if ((this.Delete_ChiTietDonHangCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Delete_ChiTietDonHangCompleted(this, new Delete_ChiTietDonHangCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Delete_SanPham", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Delete_SanPham(int ma_dh, int ma_sp) {
            object[] results = this.Invoke("Delete_SanPham", new object[] {
                        ma_dh,
                        ma_sp});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Delete_SanPhamAsync(int ma_dh, int ma_sp) {
            this.Delete_SanPhamAsync(ma_dh, ma_sp, null);
        }
        
        /// <remarks/>
        public void Delete_SanPhamAsync(int ma_dh, int ma_sp, object userState) {
            if ((this.Delete_SanPhamOperationCompleted == null)) {
                this.Delete_SanPhamOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_SanPhamOperationCompleted);
            }
            this.InvokeAsync("Delete_SanPham", new object[] {
                        ma_dh,
                        ma_sp}, this.Delete_SanPhamOperationCompleted, userState);
        }
        
        private void OnDelete_SanPhamOperationCompleted(object arg) {
            if ((this.Delete_SanPhamCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Delete_SanPhamCompleted(this, new Delete_SanPhamCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Insert_ChiTietDonHang", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Insert_ChiTietDonHang(int ma_dh, int ma_sp, int soluong, int gia) {
            object[] results = this.Invoke("Insert_ChiTietDonHang", new object[] {
                        ma_dh,
                        ma_sp,
                        soluong,
                        gia});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Insert_ChiTietDonHangAsync(int ma_dh, int ma_sp, int soluong, int gia) {
            this.Insert_ChiTietDonHangAsync(ma_dh, ma_sp, soluong, gia, null);
        }
        
        /// <remarks/>
        public void Insert_ChiTietDonHangAsync(int ma_dh, int ma_sp, int soluong, int gia, object userState) {
            if ((this.Insert_ChiTietDonHangOperationCompleted == null)) {
                this.Insert_ChiTietDonHangOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsert_ChiTietDonHangOperationCompleted);
            }
            this.InvokeAsync("Insert_ChiTietDonHang", new object[] {
                        ma_dh,
                        ma_sp,
                        soluong,
                        gia}, this.Insert_ChiTietDonHangOperationCompleted, userState);
        }
        
        private void OnInsert_ChiTietDonHangOperationCompleted(object arg) {
            if ((this.Insert_ChiTietDonHangCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Insert_ChiTietDonHangCompleted(this, new Insert_ChiTietDonHangCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Update_ChiTietDonHang", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Update_ChiTietDonHang(int ma_donhang, int ma_sp, int soluong, int gia) {
            object[] results = this.Invoke("Update_ChiTietDonHang", new object[] {
                        ma_donhang,
                        ma_sp,
                        soluong,
                        gia});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Update_ChiTietDonHangAsync(int ma_donhang, int ma_sp, int soluong, int gia) {
            this.Update_ChiTietDonHangAsync(ma_donhang, ma_sp, soluong, gia, null);
        }
        
        /// <remarks/>
        public void Update_ChiTietDonHangAsync(int ma_donhang, int ma_sp, int soluong, int gia, object userState) {
            if ((this.Update_ChiTietDonHangOperationCompleted == null)) {
                this.Update_ChiTietDonHangOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdate_ChiTietDonHangOperationCompleted);
            }
            this.InvokeAsync("Update_ChiTietDonHang", new object[] {
                        ma_donhang,
                        ma_sp,
                        soluong,
                        gia}, this.Update_ChiTietDonHangOperationCompleted, userState);
        }
        
        private void OnUpdate_ChiTietDonHangOperationCompleted(object arg) {
            if ((this.Update_ChiTietDonHangCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Update_ChiTietDonHangCompleted(this, new Update_ChiTietDonHangCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ChiTietDonHang_GetByIDCompletedEventHandler(object sender, ChiTietDonHang_GetByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChiTietDonHang_GetByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChiTietDonHang_GetByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void Delete_ChiTietDonHangCompletedEventHandler(object sender, Delete_ChiTietDonHangCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Delete_ChiTietDonHangCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Delete_ChiTietDonHangCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void Delete_SanPhamCompletedEventHandler(object sender, Delete_SanPhamCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Delete_SanPhamCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Delete_SanPhamCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void Insert_ChiTietDonHangCompletedEventHandler(object sender, Insert_ChiTietDonHangCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Insert_ChiTietDonHangCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Insert_ChiTietDonHangCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void Update_ChiTietDonHangCompletedEventHandler(object sender, Update_ChiTietDonHangCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Update_ChiTietDonHangCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Update_ChiTietDonHangCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591