//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace WindowsForms.SanPham_ServiceReferences {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SanPham_ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class SanPham_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SanPham_GetAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback SanPham_GetByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback SanPham_SearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback SanPham_GetByCategoriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback Delete_SanPhamOperationCompleted;
        
        private System.Threading.SendOrPostCallback Update_SanPhamOperationCompleted;
        
        private System.Threading.SendOrPostCallback Insert_SanPhamOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDanhMucOperationCompleted;
        
        private System.Threading.SendOrPostCallback DanhMuc_LoadOperationCompleted;
        
        private System.Threading.SendOrPostCallback SanPham_LoadOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSanPhamOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGiaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SanPham_Service() {
            this.Url = global::WindowsForms.Properties.Settings.Default.WindowsForms_SanPham_ServiceReference_SanPham_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SanPham_GetAllCompletedEventHandler SanPham_GetAllCompleted;
        
        /// <remarks/>
        public event SanPham_GetByIDCompletedEventHandler SanPham_GetByIDCompleted;
        
        /// <remarks/>
        public event SanPham_SearchCompletedEventHandler SanPham_SearchCompleted;
        
        /// <remarks/>
        public event SanPham_GetByCategoriesCompletedEventHandler SanPham_GetByCategoriesCompleted;
        
        /// <remarks/>
        public event Delete_SanPhamCompletedEventHandler Delete_SanPhamCompleted;
        
        /// <remarks/>
        public event Update_SanPhamCompletedEventHandler Update_SanPhamCompleted;
        
        /// <remarks/>
        public event Insert_SanPhamCompletedEventHandler Insert_SanPhamCompleted;
        
        /// <remarks/>
        public event GetDanhMucCompletedEventHandler GetDanhMucCompleted;
        
        /// <remarks/>
        public event DanhMuc_LoadCompletedEventHandler DanhMuc_LoadCompleted;
        
        /// <remarks/>
        public event SanPham_LoadCompletedEventHandler SanPham_LoadCompleted;
        
        /// <remarks/>
        public event GetSanPhamCompletedEventHandler GetSanPhamCompleted;
        
        /// <remarks/>
        public event GetGiaCompletedEventHandler GetGiaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SanPham_GetAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SanPham_GetAll() {
            object[] results = this.Invoke("SanPham_GetAll", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void SanPham_GetAllAsync() {
            this.SanPham_GetAllAsync(null);
        }
        
        /// <remarks/>
        public void SanPham_GetAllAsync(object userState) {
            if ((this.SanPham_GetAllOperationCompleted == null)) {
                this.SanPham_GetAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSanPham_GetAllOperationCompleted);
            }
            this.InvokeAsync("SanPham_GetAll", new object[0], this.SanPham_GetAllOperationCompleted, userState);
        }
        
        private void OnSanPham_GetAllOperationCompleted(object arg) {
            if ((this.SanPham_GetAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SanPham_GetAllCompleted(this, new SanPham_GetAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SanPham_GetByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SanPham_GetByID(int ma_sp) {
            object[] results = this.Invoke("SanPham_GetByID", new object[] {
                        ma_sp});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void SanPham_GetByIDAsync(int ma_sp) {
            this.SanPham_GetByIDAsync(ma_sp, null);
        }
        
        /// <remarks/>
        public void SanPham_GetByIDAsync(int ma_sp, object userState) {
            if ((this.SanPham_GetByIDOperationCompleted == null)) {
                this.SanPham_GetByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSanPham_GetByIDOperationCompleted);
            }
            this.InvokeAsync("SanPham_GetByID", new object[] {
                        ma_sp}, this.SanPham_GetByIDOperationCompleted, userState);
        }
        
        private void OnSanPham_GetByIDOperationCompleted(object arg) {
            if ((this.SanPham_GetByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SanPham_GetByIDCompleted(this, new SanPham_GetByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SanPham_Search", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SanPham_Search(string search) {
            object[] results = this.Invoke("SanPham_Search", new object[] {
                        search});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void SanPham_SearchAsync(string search) {
            this.SanPham_SearchAsync(search, null);
        }
        
        /// <remarks/>
        public void SanPham_SearchAsync(string search, object userState) {
            if ((this.SanPham_SearchOperationCompleted == null)) {
                this.SanPham_SearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSanPham_SearchOperationCompleted);
            }
            this.InvokeAsync("SanPham_Search", new object[] {
                        search}, this.SanPham_SearchOperationCompleted, userState);
        }
        
        private void OnSanPham_SearchOperationCompleted(object arg) {
            if ((this.SanPham_SearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SanPham_SearchCompleted(this, new SanPham_SearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SanPham_GetByCategories", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SanPham_GetByCategories(int ma_loai) {
            object[] results = this.Invoke("SanPham_GetByCategories", new object[] {
                        ma_loai});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void SanPham_GetByCategoriesAsync(int ma_loai) {
            this.SanPham_GetByCategoriesAsync(ma_loai, null);
        }
        
        /// <remarks/>
        public void SanPham_GetByCategoriesAsync(int ma_loai, object userState) {
            if ((this.SanPham_GetByCategoriesOperationCompleted == null)) {
                this.SanPham_GetByCategoriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSanPham_GetByCategoriesOperationCompleted);
            }
            this.InvokeAsync("SanPham_GetByCategories", new object[] {
                        ma_loai}, this.SanPham_GetByCategoriesOperationCompleted, userState);
        }
        
        private void OnSanPham_GetByCategoriesOperationCompleted(object arg) {
            if ((this.SanPham_GetByCategoriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SanPham_GetByCategoriesCompleted(this, new SanPham_GetByCategoriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Delete_SanPham", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Delete_SanPham(int ma_sp) {
            object[] results = this.Invoke("Delete_SanPham", new object[] {
                        ma_sp});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Delete_SanPhamAsync(int ma_sp) {
            this.Delete_SanPhamAsync(ma_sp, null);
        }
        
        /// <remarks/>
        public void Delete_SanPhamAsync(int ma_sp, object userState) {
            if ((this.Delete_SanPhamOperationCompleted == null)) {
                this.Delete_SanPhamOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_SanPhamOperationCompleted);
            }
            this.InvokeAsync("Delete_SanPham", new object[] {
                        ma_sp}, this.Delete_SanPhamOperationCompleted, userState);
        }
        
        private void OnDelete_SanPhamOperationCompleted(object arg) {
            if ((this.Delete_SanPhamCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Delete_SanPhamCompleted(this, new Delete_SanPhamCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Update_SanPham", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Update_SanPham(int ma_sp, string ten_sp, string mota, decimal gia, string hinh, int phanloai) {
            object[] results = this.Invoke("Update_SanPham", new object[] {
                        ma_sp,
                        ten_sp,
                        mota,
                        gia,
                        hinh,
                        phanloai});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Update_SanPhamAsync(int ma_sp, string ten_sp, string mota, decimal gia, string hinh, int phanloai) {
            this.Update_SanPhamAsync(ma_sp, ten_sp, mota, gia, hinh, phanloai, null);
        }
        
        /// <remarks/>
        public void Update_SanPhamAsync(int ma_sp, string ten_sp, string mota, decimal gia, string hinh, int phanloai, object userState) {
            if ((this.Update_SanPhamOperationCompleted == null)) {
                this.Update_SanPhamOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdate_SanPhamOperationCompleted);
            }
            this.InvokeAsync("Update_SanPham", new object[] {
                        ma_sp,
                        ten_sp,
                        mota,
                        gia,
                        hinh,
                        phanloai}, this.Update_SanPhamOperationCompleted, userState);
        }
        
        private void OnUpdate_SanPhamOperationCompleted(object arg) {
            if ((this.Update_SanPhamCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Update_SanPhamCompleted(this, new Update_SanPhamCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Insert_SanPham", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Insert_SanPham(string ten_sp, string mota, decimal gia, string hinh, int phanloai) {
            object[] results = this.Invoke("Insert_SanPham", new object[] {
                        ten_sp,
                        mota,
                        gia,
                        hinh,
                        phanloai});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Insert_SanPhamAsync(string ten_sp, string mota, decimal gia, string hinh, int phanloai) {
            this.Insert_SanPhamAsync(ten_sp, mota, gia, hinh, phanloai, null);
        }
        
        /// <remarks/>
        public void Insert_SanPhamAsync(string ten_sp, string mota, decimal gia, string hinh, int phanloai, object userState) {
            if ((this.Insert_SanPhamOperationCompleted == null)) {
                this.Insert_SanPhamOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsert_SanPhamOperationCompleted);
            }
            this.InvokeAsync("Insert_SanPham", new object[] {
                        ten_sp,
                        mota,
                        gia,
                        hinh,
                        phanloai}, this.Insert_SanPhamOperationCompleted, userState);
        }
        
        private void OnInsert_SanPhamOperationCompleted(object arg) {
            if ((this.Insert_SanPhamCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Insert_SanPhamCompleted(this, new Insert_SanPhamCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDanhMuc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDanhMuc(int ma_danhmuc) {
            object[] results = this.Invoke("GetDanhMuc", new object[] {
                        ma_danhmuc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDanhMucAsync(int ma_danhmuc) {
            this.GetDanhMucAsync(ma_danhmuc, null);
        }
        
        /// <remarks/>
        public void GetDanhMucAsync(int ma_danhmuc, object userState) {
            if ((this.GetDanhMucOperationCompleted == null)) {
                this.GetDanhMucOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDanhMucOperationCompleted);
            }
            this.InvokeAsync("GetDanhMuc", new object[] {
                        ma_danhmuc}, this.GetDanhMucOperationCompleted, userState);
        }
        
        private void OnGetDanhMucOperationCompleted(object arg) {
            if ((this.GetDanhMucCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDanhMucCompleted(this, new GetDanhMucCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DanhMuc_Load", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable DanhMuc_Load() {
            object[] results = this.Invoke("DanhMuc_Load", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void DanhMuc_LoadAsync() {
            this.DanhMuc_LoadAsync(null);
        }
        
        /// <remarks/>
        public void DanhMuc_LoadAsync(object userState) {
            if ((this.DanhMuc_LoadOperationCompleted == null)) {
                this.DanhMuc_LoadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDanhMuc_LoadOperationCompleted);
            }
            this.InvokeAsync("DanhMuc_Load", new object[0], this.DanhMuc_LoadOperationCompleted, userState);
        }
        
        private void OnDanhMuc_LoadOperationCompleted(object arg) {
            if ((this.DanhMuc_LoadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DanhMuc_LoadCompleted(this, new DanhMuc_LoadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SanPham_Load", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SanPham_Load() {
            object[] results = this.Invoke("SanPham_Load", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void SanPham_LoadAsync() {
            this.SanPham_LoadAsync(null);
        }
        
        /// <remarks/>
        public void SanPham_LoadAsync(object userState) {
            if ((this.SanPham_LoadOperationCompleted == null)) {
                this.SanPham_LoadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSanPham_LoadOperationCompleted);
            }
            this.InvokeAsync("SanPham_Load", new object[0], this.SanPham_LoadOperationCompleted, userState);
        }
        
        private void OnSanPham_LoadOperationCompleted(object arg) {
            if ((this.SanPham_LoadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SanPham_LoadCompleted(this, new SanPham_LoadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSanPham", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSanPham(int ma_sp) {
            object[] results = this.Invoke("GetSanPham", new object[] {
                        ma_sp});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetSanPhamAsync(int ma_sp) {
            this.GetSanPhamAsync(ma_sp, null);
        }
        
        /// <remarks/>
        public void GetSanPhamAsync(int ma_sp, object userState) {
            if ((this.GetSanPhamOperationCompleted == null)) {
                this.GetSanPhamOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSanPhamOperationCompleted);
            }
            this.InvokeAsync("GetSanPham", new object[] {
                        ma_sp}, this.GetSanPhamOperationCompleted, userState);
        }
        
        private void OnGetSanPhamOperationCompleted(object arg) {
            if ((this.GetSanPhamCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSanPhamCompleted(this, new GetSanPhamCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetGia(int ma_sp) {
            object[] results = this.Invoke("GetGia", new object[] {
                        ma_sp});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetGiaAsync(int ma_sp) {
            this.GetGiaAsync(ma_sp, null);
        }
        
        /// <remarks/>
        public void GetGiaAsync(int ma_sp, object userState) {
            if ((this.GetGiaOperationCompleted == null)) {
                this.GetGiaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGiaOperationCompleted);
            }
            this.InvokeAsync("GetGia", new object[] {
                        ma_sp}, this.GetGiaOperationCompleted, userState);
        }
        
        private void OnGetGiaOperationCompleted(object arg) {
            if ((this.GetGiaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGiaCompleted(this, new GetGiaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SanPham_GetAllCompletedEventHandler(object sender, SanPham_GetAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SanPham_GetAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SanPham_GetAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SanPham_GetByIDCompletedEventHandler(object sender, SanPham_GetByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SanPham_GetByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SanPham_GetByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SanPham_SearchCompletedEventHandler(object sender, SanPham_SearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SanPham_SearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SanPham_SearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SanPham_GetByCategoriesCompletedEventHandler(object sender, SanPham_GetByCategoriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SanPham_GetByCategoriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SanPham_GetByCategoriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void Delete_SanPhamCompletedEventHandler(object sender, Delete_SanPhamCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Delete_SanPhamCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Delete_SanPhamCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void Update_SanPhamCompletedEventHandler(object sender, Update_SanPhamCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Update_SanPhamCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Update_SanPhamCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void Insert_SanPhamCompletedEventHandler(object sender, Insert_SanPhamCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Insert_SanPhamCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Insert_SanPhamCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetDanhMucCompletedEventHandler(object sender, GetDanhMucCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDanhMucCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDanhMucCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DanhMuc_LoadCompletedEventHandler(object sender, DanhMuc_LoadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DanhMuc_LoadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DanhMuc_LoadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SanPham_LoadCompletedEventHandler(object sender, SanPham_LoadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SanPham_LoadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SanPham_LoadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetSanPhamCompletedEventHandler(object sender, GetSanPhamCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSanPhamCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSanPhamCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetGiaCompletedEventHandler(object sender, GetGiaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGiaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGiaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591