//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.KhachHang_Service {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KhachHang_Service.KhachHang_ServiceSoap")]
    public interface KhachHang_ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KhachHang_CheckLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable KhachHang_CheckLogin(string username, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KhachHang_GetAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable KhachHang_GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KhachHang_GetByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable KhachHang_GetByID(int ma_kh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KhachHang_GetByName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable KhachHang_GetByName(string ten_kh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KhachHang_GetByUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable KhachHang_GetByUsername(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KhachHang_CheckUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable KhachHang_CheckUsername(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_KhachHang", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Delete_KhachHang(int ma_kh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_KhachHang", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Update_KhachHang(int ma_kh, string hoten, string sdt, string diachi, string email, string username, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_KhachHang", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Insert_KhachHang(string hoten, string sdt, string diachi, string email, string username, string pass);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KhachHang_ServiceSoapChannel : Website.KhachHang_Service.KhachHang_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KhachHang_ServiceSoapClient : System.ServiceModel.ClientBase<Website.KhachHang_Service.KhachHang_ServiceSoap>, Website.KhachHang_Service.KhachHang_ServiceSoap {
        
        public KhachHang_ServiceSoapClient() {
        }
        
        public KhachHang_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KhachHang_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KhachHang_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KhachHang_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable KhachHang_CheckLogin(string username, string pass) {
            return base.Channel.KhachHang_CheckLogin(username, pass);
        }
        
        public System.Data.DataTable KhachHang_GetAll() {
            return base.Channel.KhachHang_GetAll();
        }
        
        public System.Data.DataTable KhachHang_GetByID(int ma_kh) {
            return base.Channel.KhachHang_GetByID(ma_kh);
        }
        
        public System.Data.DataTable KhachHang_GetByName(string ten_kh) {
            return base.Channel.KhachHang_GetByName(ten_kh);
        }
        
        public System.Data.DataTable KhachHang_GetByUsername(string username) {
            return base.Channel.KhachHang_GetByUsername(username);
        }
        
        public System.Data.DataTable KhachHang_CheckUsername(string username) {
            return base.Channel.KhachHang_CheckUsername(username);
        }
        
        public bool Delete_KhachHang(int ma_kh) {
            return base.Channel.Delete_KhachHang(ma_kh);
        }
        
        public bool Update_KhachHang(int ma_kh, string hoten, string sdt, string diachi, string email, string username, string pass) {
            return base.Channel.Update_KhachHang(ma_kh, hoten, sdt, diachi, email, username, pass);
        }
        
        public bool Insert_KhachHang(string hoten, string sdt, string diachi, string email, string username, string pass) {
            return base.Channel.Insert_KhachHang(hoten, sdt, diachi, email, username, pass);
        }
    }
}
