//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERVICE.Connect_ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Connect_ServiceReference.Connect_ServiceSoap")]
    public interface Connect_ServiceSoap {
        
        // CODEGEN: Generating message contract since element name ChuoiKetNoiResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChuoiKetNoi", ReplyAction="*")]
        SERVICE.Connect_ServiceReference.ChuoiKetNoiResponse ChuoiKetNoi(SERVICE.Connect_ServiceReference.ChuoiKetNoiRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChuoiKetNoiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChuoiKetNoi", Namespace="http://tempuri.org/", Order=0)]
        public SERVICE.Connect_ServiceReference.ChuoiKetNoiRequestBody Body;
        
        public ChuoiKetNoiRequest() {
        }
        
        public ChuoiKetNoiRequest(SERVICE.Connect_ServiceReference.ChuoiKetNoiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ChuoiKetNoiRequestBody {
        
        public ChuoiKetNoiRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChuoiKetNoiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChuoiKetNoiResponse", Namespace="http://tempuri.org/", Order=0)]
        public SERVICE.Connect_ServiceReference.ChuoiKetNoiResponseBody Body;
        
        public ChuoiKetNoiResponse() {
        }
        
        public ChuoiKetNoiResponse(SERVICE.Connect_ServiceReference.ChuoiKetNoiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChuoiKetNoiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ChuoiKetNoiResult;
        
        public ChuoiKetNoiResponseBody() {
        }
        
        public ChuoiKetNoiResponseBody(string ChuoiKetNoiResult) {
            this.ChuoiKetNoiResult = ChuoiKetNoiResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Connect_ServiceSoapChannel : SERVICE.Connect_ServiceReference.Connect_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Connect_ServiceSoapClient : System.ServiceModel.ClientBase<SERVICE.Connect_ServiceReference.Connect_ServiceSoap>, SERVICE.Connect_ServiceReference.Connect_ServiceSoap {
        
        public Connect_ServiceSoapClient() {
        }
        
        public Connect_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Connect_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Connect_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Connect_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SERVICE.Connect_ServiceReference.ChuoiKetNoiResponse SERVICE.Connect_ServiceReference.Connect_ServiceSoap.ChuoiKetNoi(SERVICE.Connect_ServiceReference.ChuoiKetNoiRequest request) {
            return base.Channel.ChuoiKetNoi(request);
        }
        
        public string ChuoiKetNoi() {
            SERVICE.Connect_ServiceReference.ChuoiKetNoiRequest inValue = new SERVICE.Connect_ServiceReference.ChuoiKetNoiRequest();
            inValue.Body = new SERVICE.Connect_ServiceReference.ChuoiKetNoiRequestBody();
            SERVICE.Connect_ServiceReference.ChuoiKetNoiResponse retVal = ((SERVICE.Connect_ServiceReference.Connect_ServiceSoap)(this)).ChuoiKetNoi(inValue);
            return retVal.Body.ChuoiKetNoiResult;
        }
    }
}
