//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.DonHang_Service {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DonHang_Service.DonHang_ServiceSoap")]
    public interface DonHang_ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DonHang_GetAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable DonHang_GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInfo_KhachHang", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetInfo_KhachHang(int ma_kh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DonHang_GetByDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable DonHang_GetByDate(System.DateTime fromDay, System.DateTime toDay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DonHang_GetByCustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable DonHang_GetByCustomer(int ma_kh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_DonHang", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Delete_DonHang(int ma_dh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_DonHang", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Update_DonHang(int ma_donhang, string tinh_trang, int ma_nv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_DonHang", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Insert_DonHang(System.DateTime ngay_dh, string tinh_trang, int ma_kh, int ma_nv);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DonHang_ServiceSoapChannel : Website.DonHang_Service.DonHang_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DonHang_ServiceSoapClient : System.ServiceModel.ClientBase<Website.DonHang_Service.DonHang_ServiceSoap>, Website.DonHang_Service.DonHang_ServiceSoap {
        
        public DonHang_ServiceSoapClient() {
        }
        
        public DonHang_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DonHang_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DonHang_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DonHang_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable DonHang_GetAll() {
            return base.Channel.DonHang_GetAll();
        }
        
        public System.Data.DataTable GetInfo_KhachHang(int ma_kh) {
            return base.Channel.GetInfo_KhachHang(ma_kh);
        }
        
        public System.Data.DataTable DonHang_GetByDate(System.DateTime fromDay, System.DateTime toDay) {
            return base.Channel.DonHang_GetByDate(fromDay, toDay);
        }
        
        public System.Data.DataTable DonHang_GetByCustomer(int ma_kh) {
            return base.Channel.DonHang_GetByCustomer(ma_kh);
        }
        
        public bool Delete_DonHang(int ma_dh) {
            return base.Channel.Delete_DonHang(ma_dh);
        }
        
        public bool Update_DonHang(int ma_donhang, string tinh_trang, int ma_nv) {
            return base.Channel.Update_DonHang(ma_donhang, tinh_trang, ma_nv);
        }
        
        public bool Insert_DonHang(System.DateTime ngay_dh, string tinh_trang, int ma_kh, int ma_nv) {
            return base.Channel.Insert_DonHang(ngay_dh, tinh_trang, ma_kh, ma_nv);
        }
    }
}
