//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace WindowsForms.NhanVien_ServiceReferences {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NhanVien_ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class NhanVien_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CheckLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback NhanVien_GetAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback NhanVien_GetByNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback Delete_NhanVienOperationCompleted;
        
        private System.Threading.SendOrPostCallback Update_NhanVienOperationCompleted;
        
        private System.Threading.SendOrPostCallback Insert_NhanVienOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NhanVien_Service() {
            this.Url = global::WindowsForms.Properties.Settings.Default.WindowsForms_NhanVien_ServiceReferences_NhanVien_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CheckLoginCompletedEventHandler CheckLoginCompleted;
        
        /// <remarks/>
        public event NhanVien_GetAllCompletedEventHandler NhanVien_GetAllCompleted;
        
        /// <remarks/>
        public event NhanVien_GetByNameCompletedEventHandler NhanVien_GetByNameCompleted;
        
        /// <remarks/>
        public event Delete_NhanVienCompletedEventHandler Delete_NhanVienCompleted;
        
        /// <remarks/>
        public event Update_NhanVienCompletedEventHandler Update_NhanVienCompleted;
        
        /// <remarks/>
        public event Insert_NhanVienCompletedEventHandler Insert_NhanVienCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable CheckLogin(string acc, string pass) {
            object[] results = this.Invoke("CheckLogin", new object[] {
                        acc,
                        pass});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void CheckLoginAsync(string acc, string pass) {
            this.CheckLoginAsync(acc, pass, null);
        }
        
        /// <remarks/>
        public void CheckLoginAsync(string acc, string pass, object userState) {
            if ((this.CheckLoginOperationCompleted == null)) {
                this.CheckLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckLoginOperationCompleted);
            }
            this.InvokeAsync("CheckLogin", new object[] {
                        acc,
                        pass}, this.CheckLoginOperationCompleted, userState);
        }
        
        private void OnCheckLoginOperationCompleted(object arg) {
            if ((this.CheckLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckLoginCompleted(this, new CheckLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NhanVien_GetAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable NhanVien_GetAll() {
            object[] results = this.Invoke("NhanVien_GetAll", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void NhanVien_GetAllAsync() {
            this.NhanVien_GetAllAsync(null);
        }
        
        /// <remarks/>
        public void NhanVien_GetAllAsync(object userState) {
            if ((this.NhanVien_GetAllOperationCompleted == null)) {
                this.NhanVien_GetAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNhanVien_GetAllOperationCompleted);
            }
            this.InvokeAsync("NhanVien_GetAll", new object[0], this.NhanVien_GetAllOperationCompleted, userState);
        }
        
        private void OnNhanVien_GetAllOperationCompleted(object arg) {
            if ((this.NhanVien_GetAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NhanVien_GetAllCompleted(this, new NhanVien_GetAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NhanVien_GetByName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable NhanVien_GetByName(string ten_nv) {
            object[] results = this.Invoke("NhanVien_GetByName", new object[] {
                        ten_nv});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void NhanVien_GetByNameAsync(string ten_nv) {
            this.NhanVien_GetByNameAsync(ten_nv, null);
        }
        
        /// <remarks/>
        public void NhanVien_GetByNameAsync(string ten_nv, object userState) {
            if ((this.NhanVien_GetByNameOperationCompleted == null)) {
                this.NhanVien_GetByNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNhanVien_GetByNameOperationCompleted);
            }
            this.InvokeAsync("NhanVien_GetByName", new object[] {
                        ten_nv}, this.NhanVien_GetByNameOperationCompleted, userState);
        }
        
        private void OnNhanVien_GetByNameOperationCompleted(object arg) {
            if ((this.NhanVien_GetByNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NhanVien_GetByNameCompleted(this, new NhanVien_GetByNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Delete_NhanVien", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Delete_NhanVien(int ma_nv) {
            object[] results = this.Invoke("Delete_NhanVien", new object[] {
                        ma_nv});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Delete_NhanVienAsync(int ma_nv) {
            this.Delete_NhanVienAsync(ma_nv, null);
        }
        
        /// <remarks/>
        public void Delete_NhanVienAsync(int ma_nv, object userState) {
            if ((this.Delete_NhanVienOperationCompleted == null)) {
                this.Delete_NhanVienOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_NhanVienOperationCompleted);
            }
            this.InvokeAsync("Delete_NhanVien", new object[] {
                        ma_nv}, this.Delete_NhanVienOperationCompleted, userState);
        }
        
        private void OnDelete_NhanVienOperationCompleted(object arg) {
            if ((this.Delete_NhanVienCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Delete_NhanVienCompleted(this, new Delete_NhanVienCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Update_NhanVien", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Update_NhanVien(int ma_nv, string ten_nv, string sdt, string diachi, string email, string acccount, string pass) {
            object[] results = this.Invoke("Update_NhanVien", new object[] {
                        ma_nv,
                        ten_nv,
                        sdt,
                        diachi,
                        email,
                        acccount,
                        pass});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Update_NhanVienAsync(int ma_nv, string ten_nv, string sdt, string diachi, string email, string acccount, string pass) {
            this.Update_NhanVienAsync(ma_nv, ten_nv, sdt, diachi, email, acccount, pass, null);
        }
        
        /// <remarks/>
        public void Update_NhanVienAsync(int ma_nv, string ten_nv, string sdt, string diachi, string email, string acccount, string pass, object userState) {
            if ((this.Update_NhanVienOperationCompleted == null)) {
                this.Update_NhanVienOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdate_NhanVienOperationCompleted);
            }
            this.InvokeAsync("Update_NhanVien", new object[] {
                        ma_nv,
                        ten_nv,
                        sdt,
                        diachi,
                        email,
                        acccount,
                        pass}, this.Update_NhanVienOperationCompleted, userState);
        }
        
        private void OnUpdate_NhanVienOperationCompleted(object arg) {
            if ((this.Update_NhanVienCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Update_NhanVienCompleted(this, new Update_NhanVienCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Insert_NhanVien", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Insert_NhanVien(string ten_nv, string sdt, string diachi, string email, string acccount, string pass) {
            object[] results = this.Invoke("Insert_NhanVien", new object[] {
                        ten_nv,
                        sdt,
                        diachi,
                        email,
                        acccount,
                        pass});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Insert_NhanVienAsync(string ten_nv, string sdt, string diachi, string email, string acccount, string pass) {
            this.Insert_NhanVienAsync(ten_nv, sdt, diachi, email, acccount, pass, null);
        }
        
        /// <remarks/>
        public void Insert_NhanVienAsync(string ten_nv, string sdt, string diachi, string email, string acccount, string pass, object userState) {
            if ((this.Insert_NhanVienOperationCompleted == null)) {
                this.Insert_NhanVienOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsert_NhanVienOperationCompleted);
            }
            this.InvokeAsync("Insert_NhanVien", new object[] {
                        ten_nv,
                        sdt,
                        diachi,
                        email,
                        acccount,
                        pass}, this.Insert_NhanVienOperationCompleted, userState);
        }
        
        private void OnInsert_NhanVienOperationCompleted(object arg) {
            if ((this.Insert_NhanVienCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Insert_NhanVienCompleted(this, new Insert_NhanVienCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CheckLoginCompletedEventHandler(object sender, CheckLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void NhanVien_GetAllCompletedEventHandler(object sender, NhanVien_GetAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NhanVien_GetAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NhanVien_GetAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void NhanVien_GetByNameCompletedEventHandler(object sender, NhanVien_GetByNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NhanVien_GetByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NhanVien_GetByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void Delete_NhanVienCompletedEventHandler(object sender, Delete_NhanVienCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Delete_NhanVienCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Delete_NhanVienCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void Update_NhanVienCompletedEventHandler(object sender, Update_NhanVienCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Update_NhanVienCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Update_NhanVienCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void Insert_NhanVienCompletedEventHandler(object sender, Insert_NhanVienCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Insert_NhanVienCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Insert_NhanVienCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591